name: Jillustrations
favicon: null
layout_spectrum: 1
typography_spectrum: 0.07066
title: Online Portfolio and Blog
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eae8d2'
    - '#f3c12d'
    - '#5f200c'
    - '#cc8d3a'
    - '#a45e1b'
  brandStrength: 0.25
  lightness: 0.75
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
